name: Unit-Test-with-Test-Reporter-Action

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Pytest
        run: |
          pytest -s -v -l test_calculator.py --junit-xml=test-results.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Unit Tests # Name of the check run which will be created
          path: "*.xml" # Path to test results
          reporter: jest-junit
